[package]
name          = "alto_logger"
version       = "0.1.0"
edition       = "2018"

authors       = ["museun <museun@outlook.com>"]
repository    = "https://github.com/museun/alto_logger"
documentation = "https://docs.rs/alto_logger"

description   = "an opinionated logger that provides colorful and multi-line output"

license       = "0BSD"
readme        = "README.md"

keywords      = ["log", "logging", "logger"]
categories    = ["development-tools::debugging"]


[dependencies]
log       = "0.4.8"
termcolor = "1.1.0"
once_cell = "1.3.1"
